const char* stopwordsArray [] = {"a","b", "c","d","e","f","g","h","j","k","l","m",">>>",">>",">",
    "o","p","q","r","s","t","u","v","w","x","z","y","able","about","across","after","all","almost","also","am",
    "among","an","and","any","are2706","as","at","be","because","been","but","by","can","cannot","could","dear",
    "did","do","does","either","else","ever","every","for","from","get","got","had","he","her",
    "hers","him","his","how","however","i","if","in","into","is","its","just","let","like",
    "likely","may","me","might","most","must","my","neither","no","nor","not","of","off","often","on","only",
    "or","other","our","own","rather","said","say","says","she","should","since","so","some","than","that",
    "the","their","them","then","there","these","they","tis","to","too","twas","us","wants","was","we",
    "were","what","when","where","which","while","who","whom","why","will","with","would","yet","you","your",
    "a","able","about","across","after","aint","all","almost","also","am","among","an","and",
    "any","are","arent","as","at","be","because","been","but","by","can","cant","cannot","could","couldve",
    "couldnt","dear","did","didnt","do","does","doesnt","dont","either","else","ever","every","for",
    "from","get","got","hasnt","have","he","hed","hell","hes","her","hers","him","his","how",
    "howd","howll","hows","however","i","id","ill","im","ive","if","in","into","is","isnt",
    "just","least","let","like","likely","may","me","might","mightve","mightnt","most","mustve",
    "mustnt","my","neither","no","nor","not","of","off","often","on","only","or","other","our","own",
    "rather","said","say","says","shant","she","shed","shell","shes","should","shouldve","shouldnt",
    "since","so","some","than","that","thatll","thats","the","their","them","then","there","theres"
    ,"they","theyd","theyre","this","tis","to","too","twas","us","wants","was",
    "wasnt","we","wed","well","were","were","werent","what","whatd","whats","whend","whenll",
    "whens","where","whered","wherell","wheres","which","who","whod","wholl","whos","whom",
    "whyd","whyll","whys","with","wont","would","wouldve","wouldnt","yet","you","youd",
    "youll","youre","youve","aint","arent","cant","couldve","couldnt","didnt",
    "doesnt","dot","hes","howd","howll","hows","id","ill","im","ive","isnt","its","mightve",
    "mightnt","shant","shed","shell","shes","shouldve","shouldnt","thatll","thats","theres",
    "theyd","wasnt","wed","well","were","werent","whatd","whats",
    "whered","wherell","wheres","whod","wholl","whos","wont","wouldve",
    "wouldnt","youd","youll","youre","youve","I","com","de","en","la","und","www", "inhibit","limits" ,
    "throttling","set", "review", "cause", "old","able","about","above","abroad","according","accordingly",
    "against","abroad","ahead","aint","all","allow","allows","almost","alone","along","alongside","already",
    "also","although","always","am","amid","amidst","among","amongst","alongside","and","another","any",
    "anybody","anyhow","anyone","anything","anyway","anyways","anywhere","apart","appear","appreciate",
    "appropriate","are","arent","around","as","anyways","aside","ask","asking","associated","at","available",
    "away","awfully","back","backward","backwards","be","became","because","become","becomes","becoming",
    "been","back","beforehand","begin","behind","being","believe","below","beside","besides","best","better",
    "between","beyond","both","brief","but","by","came","can","best","cant","cant","caption","cause",
    "causes","certain","certainly","changes","clearly","co","co.","com","come","comes","concerning",
    "consequently","consider","clearly","contain","containing","contains","corresponding","could","couldnt",
    "course","cs","currently","dare","darent","definitely","described","despite","did","didnt","different",
    "directly","currently","does","doesnt","doing","done","dont","down","downwards","during","each","edu",
    "eg","eight","eighty","either","else","elsewhere","end","ending","each","entirely","especially","et",
    "etc","even","ever","evermore","every","everybody","everyone","everything","everywhere","ex","exactly",
    "example","except","fairly","far","everybody","few","fewer","fifth","first","five","followed","following",
    "follows","for","forever","former","formerly","forth","forward","found","four","from","further","for",
    "get","gets","getting","given","gives","go","goes","going","gone","got","gotten","greetings","hase",
    "hadnt","half","happens","hardly","has","gone","havent","having","he","hed","hell","hello",
    "help","hence","her","here","hereafter","hereby","herein","heres","hereupon","hers","herself","hence",
    "hi","him","himself","his","hither","hopefully","how","howbeit","however","hundred","ie","if",
    "ignored","im","immediate","in","however","inc","inc.","indeed","indicate","indicated","it"
    "indicates","inner","inside","insofar","instead","into","inward","is","isnt","it","itd","itll",
    "insofar","itself","ive","just","k","keep","keep","keeps","kept","know","known","knows","last",
    "lately","later","latter","latterly","less","know","let","lets","like","liked","likely",
    "likewise","little","look","looking","looks","low","lower","ltd","made","mainly","make","makes","many",
    "looking","maybe","maynt","me","mean","meantime","meanwhile","merely","might","mightnt","mine","minus",
    "miss","more","moreover","most","mostly","mr","mrs","mightnt","must","mustnt","my","myself","name",
    "namely","nd","near","nearly","necessary","need","neednt","needs","neither","never","neverf","neverless",
    "nevertheless","nearly","next","nine","ninety","no","nobody","non","none","nonetheless","noone",
    "no-one","nor","normally","not","nothing","notwithstanding","novel","now","nowhere","noone","of","off",
    "often","oh","ok","okay","old","on","once","one","ones","ones","only","onto","opposite","or","other",
    "others","once","ought","oughtnt","our","ours","ourselves","out","outside","over","overall","own",
    "particular","particularly","past","per","perhaps","placed","please","plus","overall","presumably",
    "probably","provided","provides","que","quite","qv","rather","rd","re","really","reasonably","recent",
    "recently","regarding","regardless","regards","relatively","rd","right","round","said","same","saw",
    "say","saying","says","second","secondly","see","seeing","seem","seemed","seeming","seems","seen","self",
    "second","sensible","sent","serious","seriously","seven","several","shall","shant","she","shed",
    "shell","shes","should","shouldnt","since","six","so","some","she","someday","somehow","someone",
    "something","sometime","sometimes","somewhat","somewhere","soon","sorry","specified","specify",
    "specifying","still","sub","such","sup","sure","soon","taken","taking","tell","tends","th","than","thank",
    "thanks","thanx","that","thatll","thats","thats","thatve","the","their","theirs","them","thanx","then",
    "thence","there","thereafter","thereby","thered","therefore","therein","therere","theres",
    "theres","thereupon","thereve","they","theyd","theyll","therell","theyve","thing","things",
    "think","third","thirty","thorough","thoroughly","those","though","three","through","throughout",
    "thru","thus","till","to","thoroughly","too","took","toward","towards","tried","tries","truly","try",
    "trying","twice","two","un","under","underneath","undoing","unfortunately","unless","trying",
    "unlikely","until","unto","up","upon","upwards","us","use","used","useful","uses","using","usually",
    "v","value","various","versus","very","used","viz","vs","want","wants","was","wasnt","way","we","wed",
    "welcome","well","well","went","were","were","werent","weve","what","wed","whatll","whats",
    "whatve","when","whence","whenever","where","whereafter","whereas","whereby","wherein","wheres",
    "whereupon","wherever","whether","which","whichever","whereas","whither","who","whod",
    "whoever","whole","wholl","whom","whomever","whos","whose","why","willing","wish","with",
    "within","without","wonder","whos","would","wouldnt","yes","yet","you","youd","youll","your",
    "youre","yours","yourself","yourselves","youve", "across","actually","adj","after","afterwards",
    "re", "-lrb-", "``" , "`", "-rrb-", "mccain", "thi" , "sai","starr",
     "%" , "cnn" , "wa", "-LRB-", "-RRB-", "rrb", "lrb" , "governments","again", 
    "moldova", "committee", "tension", "applause", "yesterdays", "yesterday", "issue", "oil",
    "cnn.com", "council", "wave","escalation","hail", "newsroom","milton","happen" ,//cnn.com\/fan", 
    "nightfall","effort", "thousand","ambassador","greater","sort ", "day", //"\/", 
    "days","large","michael", "phelps" ,"reporter","akaiwa","hayes","dr.", "john", "curran","jatropha", "san", 
    "mr.", "ms.","gori", "south","north","west","east", "correspondent", "matthew", "chance","iphone","diego",
    "elbow", "grease","ad", "ph","...", "harri", "southern" , "isaac", "hayes" , "bachmans",
    "barbara", "sovereignty", "f.", "whitfield" , "large", "scale" , "williams", "condoleezza", "rice" ,"barack" ,
    "obama", "xxix", "caylee" , "casey" ,"surprise" , "new" ,"nan" , "sunday", "ura", "saturday","viewers"
    "dr" , "iii" , "dan" , "subnav" , "mutant" , "live" , "det" , "onus" , "rfi" , "heidi", "collin" , "harris"
    "tony" , "cam" , "gonna","sanjay","gupta","mmviii","wow","breaking","news","cbw","inn","exclusive","pixies"
    "aussie","amass","elise","call","free","coverage","developing","story", "before","kabc","wanna"
    "smm","hour","vause", "ae"};